name: Release
on:
  push:
    branches: [main,develop]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
          cache: sbt
      - run: |
          export PROG_VERSION=${GITHUB_REF_NAME} && [[ ${GITHUB_REF_TYPE} = "branch" ]]  && export PROG_VERSION=${GITHUB_REF_NAME}"-SNAPSHOT"
          echo "PROG_VERSION=$PROG_VERSION GITHUB_REF_TYPE=${GITHUB_REF_TYPE} GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "VERSION=$PROG_VERSION"
          sbt ci-release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}